const Controller = require('../controllers/controller.js');
const router = require('express').Router();

router.get('/', Controller.homePage)
// router.get('/login', Controller.loginPage)
// router.post('/login', Controller.postLoginPage)
// router.get('/logout', Controller.logout)
// router.get('/register', Controller.registerUser)
// router.post('/register', Controller.postRegisterUser)
// router.get('/user/:id/profile', Controller.userProfile)
// router.get('/user/:id/profile/update', Controller.updateUserProfile)
// router.post('/user/:id/profile/update', Controller.postUpdateUserProfile)
// router.get('/products', Controller.home)
// router.get('/user/:id/profile/edit', Controller.editUserProfile)
// router.post('/user/:id/profile/edit', Controller.postEditUserProfile)
// router.get('/transactions', Controller.showTransactions)
// router.get('/categories', Controller.showAllCategories)
// router.get('/categories/:id', Controller.showProductByCategory)
// router.get('/products/add', Controller.addProduct)
// router.post('/products/add', Controller.postAddProduct)
// router.get('/categories/:categoryId/products/:productId', Controller.showProductById)
// router.get('/products/:id/buy', Controller.buyProduct)
// router.post('/transactions', Controller.showTransactions)
// router.get('/products/:id/update', Controller.updateProduct)
// router.post('/products/:id/update', Controller.postUpdateProduct)
// router.get('/products/:id/delete', Controller.deleteProduct)
// router.get('/user/:id/topup', Controller.topupCredits)
// router.post('/user/:id/topup', Controller.postTopupCredits)
module.exports = router